# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:00
from __future__ import unicode_literals

from django.db import migrations




def _forwards_func(apps, schema_editor):
    Area = apps.get_model('raidar', 'Area')
    db_alias = schema_editor.connection.alias
    Area.objects.using(db_alias).bulk_create([
        Area(name='Vale Guardian', id=0x3C4E),
        Area(name='Gorseval', id=0x3C45),
        Area(name='Sabetha', id=0x3C0F),
        Area(name='Slothasor', id=0x3EFB),
        Area(name='Berg', id=0x3ED8),
        Area(name='Zane', id=0x3F09),
        Area(name='Narella', id=0x3EFD),
        Area(name='Matthias', id=0x3EF3),
        Area(name='Keep Construct', id=0x3F6B),
        Area(name='Xera', id=0x3F76),
        Area(name='Xera (Post-Half)', id=0x3F9E), # XXX what is this? which is real?
        Area(name='Cairn', id=0x432A),
        Area(name='Mursaat Overseer', id=0x4314),
        Area(name='Samarog', id=0x4324),
        Area(name='Deimos', id=0x4302),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('raidar', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_forwards_func),
    ]
