# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='guid',
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
    ]
