# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0006_add_defaults_to_encounter_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='guid',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
