# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 02:28
from __future__ import unicode_literals

from django.db import migrations
from time import time



def _forwards_func(apps, schema_editor):
    Era = apps.get_model('raidar', 'Era')
    Era.objects.update_or_create(id=1, defaults = {
        "name": "Prehistoric",
        "started_at": 0
    })


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0008_era'),
    ]

    operations = [
        migrations.RunPython(_forwards_func, reverse_code=migrations.RunPython.noop),
    ]
