# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 07:56
from __future__ import unicode_literals

from django.db import migrations

def gen_user_profile(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('raidar', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.update_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0008_add_encounter_gdrive_fields'),
    ]

    operations = [
        migrations.RunPython(gen_user_profile, reverse_code=migrations.RunPython.noop),
    ]
