# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models

import raidar

def gen_url_id(apps, schema_editor):
    Encounter = apps.get_model('raidar', 'Encounter')
    default_func = raidar.models._generate_url_id
    for encounter in Encounter.objects.all().iterator():
        encounter.url_id = default_func()
        encounter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0013_upload_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='url_id',
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.RunPython(gen_url_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='encounter',
            name='url_id',
            field=models.TextField(default=raidar.models._generate_url_id, editable=False, max_length=255, unique=True),
        ),
    ]
