# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0014_encounter_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.IntegerField(db_index=True, default=time.time),
        ),
    ]
