# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import raidar.models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0015_notification_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EraAreaStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='{}')),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='stats',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='url_id',
            field=models.TextField(default=raidar.models._generate_url_id, editable=False, max_length=255, unique=True, verbose_name='URL ID'),
        ),
        migrations.AddField(
            model_name='eraareastore',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='era_area_stores', to='raidar.Area'),
        ),
        migrations.AddField(
            model_name='eraareastore',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='era_area_stores', to='raidar.Era'),
        ),
    ]
