# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raidar', '0016_era_area_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='EraUserStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='{}')),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='era_user_stores', to='raidar.Era')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='era_user_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stats',
        ),
    ]
