# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0017_era_user_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='elite',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Core'), (1, 'Heart of Thorns'), (1, 'Path of Fire')], db_index=True),
        ),
    ]
