# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 02:29
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('raidar', '0021_make_privacy_trivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
