# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0026_rename_encounter_dump'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='era',
            options={'ordering': ('-started_at',)},
        ),
    ]
