# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0027_era_default_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='value',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='era',
            name='value',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='eraareastore',
            name='value',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='erauserstore',
            name='value',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='value',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.TextField(default='{}', editable=False),
        ),
    ]
