# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0028_value_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='value',
            field=models.TextField(default='{}', editable=False),
        ),
    ]
