# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0032_has_evtc_no_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='raidar.Account', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='character_name',
            field=models.CharField(db_index=True, default='', max_length=64, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='profession',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Guardian'), (2, 'Warrior'), (3, 'Engineer'), (4, 'Ranger'), (5, 'Thief'), (6, 'Elementalist'), (7, 'Mesmer'), (8, 'Necromancer'), (9, 'Revenant')], db_index=True, null=True),
            preserve_default=False,
        ),
    ]
