# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0033_add_account_to_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='characters',
        ),
        migrations.AddField(
            model_name='encounter',
            name='accounts',
            field=models.ManyToManyField(related_name='encounters', through='raidar.Participation', to='raidar.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('encounter', 'account')]),
        ),
        migrations.RemoveField(
            model_name='participation',
            name='character',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='character_name',
            new_name='character',
        ),
    ]
