# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0036_remove_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='raidar.Account'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='character',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='participation',
            name='profession',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Guardian'), (2, 'Warrior'), (3, 'Engineer'), (4, 'Ranger'), (5, 'Thief'), (6, 'Elementalist'), (7, 'Mesmer'), (8, 'Necromancer'), (9, 'Revenant')], db_index=True),
        ),
    ]
