# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0038_new_django'),
        ('raidar', '0038_auto_20171209_1411'),
    ]

    operations = [
    ]
