# Generated by Django 2.2.3 on 2019-07-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0040_eraareastore_leaderboards_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestatPerfStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField()),
                ('ended_on', models.DateTimeField()),
                ('number_users', models.IntegerField()),
                ('number_eras', models.IntegerField()),
                ('number_areas', models.IntegerField()),
                ('number_new_encounters', models.IntegerField()),
                ('was_force', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Squad'), (3, 'Public')], default=2, editable=False),
        ),
    ]
