# Generated by Django 2.2.3 on 2019-08-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0041_restat_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.TextField()),
                ('cm', models.BooleanField()),
                ('start_timestamp', models.DateTimeField()),
                ('start_tick', models.PositiveIntegerField()),
                ('end_tick', models.PositiveIntegerField()),
                ('success', models.BooleanField()),
                ('evtc_version', models.TextField()),
            ],
            options={
                'db_table': 'raidar_encounter_data',
            },
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='value',
        ),
        migrations.CreateModel(
            name='EncounterPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.TextField()),
                ('character', models.TextField()),
                ('party', models.PositiveIntegerField()),
                ('profession', models.PositiveIntegerField()),
                ('elite', models.PositiveIntegerField()),
                ('archetype', models.PositiveIntegerField()),
                ('conc', models.PositiveIntegerField()),
                ('condi', models.PositiveIntegerField()),
                ('heal', models.PositiveIntegerField()),
                ('tough', models.PositiveIntegerField()),
                ('death_tick', models.PositiveIntegerField(null=True)),
                ('encounter', models.ForeignKey(db_column='encounter_data_id', on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterData')),
            ],
            options={
                'db_table': 'raidar_encounter_player',
            },
        ),
        migrations.CreateModel(
            name='EncounterPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_tick', models.PositiveIntegerField()),
                ('encounter', models.ForeignKey(db_column='encounter_data_id', on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterData')),
            ],
            options={
                'db_table': 'raidar_encounter_phase',
            },
        ),
        migrations.CreateModel(
            name='EncounterMechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.TextField()),
                ('source', models.TextField()),
                ('name', models.TextField()),
                ('count', models.PositiveIntegerField()),
                ('encounter', models.ForeignKey(db_column='encounter_data_id', on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterData')),
            ],
            options={
                'db_table': 'raidar_encounter_mechanic',
            },
        ),
        migrations.CreateModel(
            name='EncounterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.TextField()),
                ('source', models.TextField()),
                ('disconnect_count', models.PositiveIntegerField()),
                ('disconnect_time', models.PositiveIntegerField()),
                ('down_count', models.PositiveIntegerField()),
                ('down_time', models.PositiveIntegerField()),
                ('encounter', models.ForeignKey(db_column='encounter_data_id', on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterData')),
            ],
            options={
                'db_table': 'raidar_encounter_event',
            },
        ),
        migrations.CreateModel(
            name='EncounterDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.TextField()),
                ('source', models.TextField()),
                ('target', models.TextField()),
                ('skill', models.TextField()),
                ('damage', models.IntegerField()),
                ('crit', models.FloatField()),
                ('fifty', models.FloatField()),
                ('flanking', models.FloatField()),
                ('scholar', models.FloatField()),
                ('seaweed', models.FloatField()),
                ('encounter', models.ForeignKey(db_column='encounter_data_id', on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterData')),
            ],
            options={
                'db_table': 'raidar_encounter_damage',
            },
        ),
        migrations.CreateModel(
            name='EncounterBuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.TextField()),
                ('source', models.TextField()),
                ('target', models.TextField()),
                ('name', models.TextField()),
                ('uptime', models.FloatField()),
                ('encounter', models.ForeignKey(db_column='encounter_data_id', on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterData')),
            ],
            options={
                'db_table': 'raidar_encounter_buff',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounter_data',
            field=models.ForeignKey(db_column='encounter_data_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterData'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='encounterplayer',
            constraint=models.UniqueConstraint(fields=('encounter', 'account_id'), name='enc_player_unique'),
        ),
        migrations.AddConstraint(
            model_name='encounterphase',
            constraint=models.UniqueConstraint(fields=('encounter', 'name'), name='enc_phase_unique'),
        ),
        migrations.AddConstraint(
            model_name='encounterevent',
            constraint=models.UniqueConstraint(fields=('encounter', 'phase', 'source'), name='enc_evt_unique'),
        ),
        migrations.AddConstraint(
            model_name='encounterdamage',
            constraint=models.UniqueConstraint(fields=('encounter', 'phase', 'source', 'target', 'skill'), name='enc_dmg_unique'),
        ),
        migrations.AddConstraint(
            model_name='encounterbuff',
            constraint=models.UniqueConstraint(fields=('encounter', 'phase', 'source', 'target', 'name'), name='enc_buff_unique'),
        ),
    ]
