# Generated by Django 2.2.3 on 2019-09-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0042_encounter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterbuff',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterPhase'),
        ),
        migrations.AlterField(
            model_name='encounterdamage',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterPhase'),
        ),
        migrations.AlterField(
            model_name='encounterevent',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterPhase'),
        ),
        migrations.AlterField(
            model_name='encountermechanic',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterPhase'),
        ),
    ]
