# Generated by Django 2.2.3 on 2019-09-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0044_encounter_players_account_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterdata',
            name='end_tick',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='encounterdata',
            name='start_tick',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='encounterphase',
            name='start_tick',
            field=models.BigIntegerField(),
        ),
    ]
