# Generated by Django 2.2.3 on 2019-09-11 18:24
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0045_encounter_phase_tick_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='encounter',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.now),
            preserve_default=False,
        ),
    ]
