# Generated by Django 2.2.3 on 2019-09-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0046_encounter_upload_stamp_to_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='portrait_url',
        ),
    ]
