# Generated by Django 2.2.3 on 2019-09-17 08:34

import analyser.analyser
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raidar', '0047_remove_userprofile_portrait_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'raidar_stats_squad',
            },
        ),
        migrations.AlterField(
            model_name='participation',
            name='elite',
            field=models.PositiveSmallIntegerField(choices=[(-1, 'All'), (analyser.analyser.Elite(0), 'Core'), (analyser.analyser.Elite(1), 'Heart of Thorns'), (analyser.analyser.Elite(2), 'Path of Fire')], db_index=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='profession',
            field=models.PositiveSmallIntegerField(choices=[(-1, 'All'), (analyser.analyser.Profession(1), 'Guardian'), (analyser.analyser.Profession(2), 'Warrior'), (analyser.analyser.Profession(3), 'Engineer'), (analyser.analyser.Profession(4), 'Ranger'), (analyser.analyser.Profession(5), 'Thief'), (analyser.analyser.Profession(6), 'Elementalist'), (analyser.analyser.Profession(7), 'Mesmer'), (analyser.analyser.Profession(8), 'Necromancer'), (analyser.analyser.Profession(9), 'Revenant')], db_index=True),
        ),
        migrations.AddConstraint(
            model_name='encountermechanic',
            constraint=models.UniqueConstraint(fields=('encounter_data', 'phase', 'source', 'name'), name='enc_mech_unique'),
        ),
        migrations.CreateModel(
            name='BuildStats',
            fields=[
                ('squadstats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raidar.SquadStats')),
                ('archetype', models.PositiveSmallIntegerField(choices=[(analyser.analyser.Archetype(1), 'Power'), (analyser.analyser.Archetype(2), 'Condi'), (analyser.analyser.Archetype(3), 'Tank'), (analyser.analyser.Archetype(4), 'Heal'), (analyser.analyser.Archetype(5), 'Support')], db_index=True)),
                ('profession', models.PositiveSmallIntegerField(choices=[(-1, 'All'), (analyser.analyser.Profession(1), 'Guardian'), (analyser.analyser.Profession(2), 'Warrior'), (analyser.analyser.Profession(3), 'Engineer'), (analyser.analyser.Profession(4), 'Ranger'), (analyser.analyser.Profession(5), 'Thief'), (analyser.analyser.Profession(6), 'Elementalist'), (analyser.analyser.Profession(7), 'Mesmer'), (analyser.analyser.Profession(8), 'Necromancer'), (analyser.analyser.Profession(9), 'Revenant')], db_index=True)),
                ('elite', models.PositiveSmallIntegerField(choices=[(-1, 'All'), (analyser.analyser.Elite(0), 'Core'), (analyser.analyser.Elite(1), 'Heart of Thorns'), (analyser.analyser.Elite(2), 'Path of Fire')], db_index=True)),
            ],
            options={
                'db_table': 'raidar_stats_build',
            },
            bases=('raidar.squadstats',),
        ),
        migrations.AddField(
            model_name='squadstats',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidar.Area'),
        ),
        migrations.AddField(
            model_name='squadstats',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidar.Era'),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('buildstats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raidar.BuildStats')),
            ],
            options={
                'db_table': 'raidar_stats_user',
            },
            bases=('raidar.buildstats',),
        ),
        migrations.AddConstraint(
            model_name='squadstats',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'stat', 'out'), name='stats_group_unique'),
        ),
        migrations.AddConstraint(
            model_name='buildstats',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'archetype', 'profession', 'elite', 'stat', 'out'), name='stats_group_unique'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'user', 'archetype', 'profession', 'elite', 'stat', 'out'), name='stats_group_unique'),
        ),
    ]
