# Generated by Django 2.2.3 on 2019-09-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0048_new_stat_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_data',
            field=models.OneToOneField(db_column='encounter_data_id', on_delete=django.db.models.deletion.CASCADE, to='raidar.EncounterData'),
        ),
    ]
