# Generated by Django 2.2.3 on 2019-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0048_new_era_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadstats',
            name='avg_val',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadstats',
            name='max_val',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadstats',
            name='min_val',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadstats',
            name='perc_data',
            field=models.TextField(default='', editable=False),
        ),
    ]
