# Generated by Django 2.2.3 on 2019-09-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0049_stats_add_percentile_autocalculation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='buildstats',
            name='stats_group_unique',
        ),
        migrations.RemoveConstraint(
            model_name='squadstats',
            name='stats_group_unique',
        ),
        migrations.RemoveConstraint(
            model_name='userstats',
            name='stats_group_unique',
        ),
        migrations.RenameField(
            model_name='buildstats',
            old_name='profession',
            new_name='prof',
        ),
        migrations.AddField(
            model_name='squadstats',
            name='out',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadstats',
            name='phase',
            field=models.TextField(default='All'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadstats',
            name='stat',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='buildstats',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'phase', 'archetype', 'prof', 'elite', 'stat', 'out'), name='stats_group_unique'),
        ),
        migrations.AddConstraint(
            model_name='squadstats',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'phase', 'stat', 'out'), name='stats_group_unique'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'phase', 'user', 'archetype', 'prof', 'elite', 'stat', 'out'), name='stats_group_unique'),
        ),
    ]
