# Generated by Django 2.2.3 on 2019-10-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0049_encounter_data_as_onetoone_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eraareastore',
            name='area',
        ),
        migrations.RemoveField(
            model_name='eraareastore',
            name='era',
        ),
        migrations.AddField(
            model_name='buildstat',
            name='group',
            field=models.TextField(default='target'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadstat',
            name='group',
            field=models.TextField(default='target'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstat',
            name='group',
            field=models.TextField(default='target'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildstat',
            name='avg_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='buildstat',
            name='max_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='buildstat',
            name='min_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='buildstat',
            name='perc_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='squadstat',
            name='avg_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='squadstat',
            name='max_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='squadstat',
            name='min_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='squadstat',
            name='perc_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='avg_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='max_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='min_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='perc_data',
            field=models.TextField(default=''),
        ),
        migrations.AddConstraint(
            model_name='squadstat',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'phase', 'name', 'out'), name='stats_group_unique'),
        ),
        migrations.DeleteModel(
            name='EraAreaStore',
        ),
    ]
