# Generated by Django 2.2.3 on 2019-10-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidar', '0050_add_stat_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='buildstat',
            name='stats_build_unique',
        ),
        migrations.RemoveConstraint(
            model_name='squadstat',
            name='stats_group_unique',
        ),
        migrations.RemoveConstraint(
            model_name='userstat',
            name='stats_user_unique',
        ),
        migrations.AddConstraint(
            model_name='buildstat',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'phase', 'archetype', 'prof', 'elite', 'group', 'name', 'out'), name='stats_build_unique'),
        ),
        migrations.AddConstraint(
            model_name='squadstat',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'phase', 'group', 'name', 'out'), name='stats_group_unique'),
        ),
        migrations.AddConstraint(
            model_name='userstat',
            constraint=models.UniqueConstraint(fields=('era', 'area', 'phase', 'user', 'archetype', 'prof', 'elite', 'group', 'name', 'out'), name='stats_user_unique'),
        ),
    ]
