//loadReplay('replay-canvas', 'test.json')
var replayvg = new Replay('#replay-vg', 800, 400)
var replaygorse = new Replay('#replay-gorse', 800, 400)
var replaysab = new Replay('#replay-sab', 800, 400)
var replaysloth = new Replay('#replay-sloth', 800, 400)
var replaymatt = new Replay('#replay-matt', 800, 400)
var replaykc = new Replay('#replay-kc', 800, 400)
var replayxera = new Replay('#replay-xera', 800, 400)
var replaycairn = new Replay('#replay-cairn', 800, 400)
var replaymo = new Replay('#replay-mo', 800, 400)
var replaysam = new Replay('#replay-sam', 800, 400)
var replaydeimos = new Replay('#replay-deimos', 800, 400)
var replaysh = new Replay('#replay-sh', 800, 400)
var replaydhuum = new Replay('#replay-dhuum', 800, 400)
replayvg.loadReplay('vg.json')
replaysh.loadReplay('sh.json')
replaygorse.loadReplay('gorse.json')
replaysab.loadReplay('sab.json')
replaysloth.loadReplay('sloth.json')
replaymatt.loadReplay('test.json')
